version: '3.8'

# Este é o arquivo docker-compose.yml principal do DataLab.
# Ele foi reestruturado para maior escalabilidade e desacoplamento.
# Agora, os serviços estão separados em arquivos específicos por funcionalidade:
#
# - docker-compose.core.yml:        Serviços de infraestrutura core (MinIO, Kafka, Consul)
# - docker-compose.processing.yml:  Serviços de processamento de dados (Spark, NiFi)
# - docker-compose.ml.yml:          Serviços de machine learning (MLflow, Prefect, Airflow)
# - docker-compose.visualization.yml: Serviços de visualização (JupyterHub, Streamlit)
# - docker-compose.monitoring.yml:    Serviços de monitoramento (Prometheus, Grafana)
#
# Para iniciar serviços específicos ou todos os serviços, use o script:
# ./scripts/manage_environments.sh
#
# Exemplos de uso:
# ./scripts/manage_environments.sh start core
# ./scripts/manage_environments.sh start core processing
# ./scripts/manage_environments.sh start all
# ./scripts/manage_environments.sh stop ml
#
# Para ver o status dos serviços em execução:
# ./scripts/manage_environments.sh status