version: '3.8'

# DataLab - Core Services Only (for testing)
# Simplified version focusing on essential services

services:
  # ====================================
  # STORAGE SERVICES
  # ====================================
  
  # MinIO (S3-compatible object storage)
  minio:
    image: bitnami/minio:latest
    container_name: datalab-minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/bitnami/minio/data
    networks:
      - datalab-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ====================================
  # ML SERVICES
  # ====================================
  
  # MLflow (ML Lifecycle Management)
  mlflow:
    build:
      context: ./config/mlflow
      dockerfile: Dockerfile
    container_name: datalab-mlflow
    command: ["/opt/bitnami/python/bin/mlflow", "server", "--host", "0.0.0.0", "--backend-store-uri", "sqlite:////opt/mlflow/mlflow.db", "--default-artifact-root", "s3://mlflow/artifacts/"]
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    volumes:
      - mlflow-data:/opt/mlflow
    networks:
      - datalab-network
    depends_on:
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5

  # ====================================
  # JUPYTER NOTEBOOK
  # ====================================
  
  # JupyterLab (Simple version without PySpark)
  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: datalab-jupyter
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=datalab123
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    volumes:
      - ./notebooks:/home/jovyan/work
    networks:
      - datalab-network
    depends_on:
      - minio
      - mlflow

  # ====================================
  # WEB APPLICATIONS
  # ====================================
  
  # Streamlit (Simplified version)
  streamlit:
    image: python:3.11-slim
    container_name: datalab-streamlit
    working_dir: /app
    command: >
      bash -c "
        pip install streamlit pandas plotly boto3 mlflow requests &&
        streamlit run app.py --server.port=8501 --server.address=0.0.0.0
      "
    ports:
      - "8501:8501"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    volumes:
      - ./app:/app
    networks:
      - datalab-network
    depends_on:
      - mlflow
      - minio

# ====================================
# NETWORKS
# ====================================
networks:
  datalab-network:
    driver: bridge

# ====================================
# VOLUMES
# ====================================
volumes:
  minio-data:
    driver: local
  mlflow-data:
    driver: local
